matrix:
  include:
    - language: node_js
      node_js:
        - '12'
      cache:
        directories:
          - "$HOME/.cache/yarn"
          - "dist"
          - "node_modules"
      branches:
        only:
          - master
          - develop
      before_install:
        - export REPOROOT=$TRAVIS_BUILD_DIR
        - export PORTAL_MP_PATH=/
      before_script:
        - source ./travis.sh
        - beforeScript $PORTAL_MP_PATH
      script:
        - doScript $PORTAL_MP_PATH
      after_script:
        - afterScript $PORTAL_MP_PATH